import tile

class Piece:
    def __init__(self, id):
        if id == 0: ...
        if id == 1: ...
        if id == 2: ...
        if id == 3: ...
        if id == 4: ...
        if id == 5: ...
        if id == 6: ...


    def rotate(self):
        ...

    def move_left(self):
        ...

    def move_right(self):
        ...

    def move_down(self):
        ...

    def draw(self):
        ...